Migrate to Silk.NET
After testing in PoC project, OpenTK doesn't seem to work in browser and throws this exception:

System.TypeInitializationException: TypeInitialization_Type, OpenTK.Graphics.OpenGL.GL
 ---> System.PlatformNotSupportedException: No native to managed transition for method 'void OpenTK.Graphics.BindingsBase:Uninitialized ()', missing [UnmanagedCallersOnly] attribute.
   at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(Delegate d)
   at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate[Action](Action d)
   at OpenTK.Graphics.BindingsBase.InitializeDummyEntryPoints(IntPtr[] entryPoints)
   at OpenTK.Graphics.OpenGL.GL..cctor()
   Exception_EndOfInnerExceptionStack
   at AvaGLPoc.OpenGL.GlVisualHandler.OnRender(ImmediateDrawingContext drawingContext) in C:\...\GlVisualHandler.cs:line 90